language: cpp
os:
    - linux
    - osx
    - windows
dist:
    - bionic
osx_image:
    - xcode11.3
env:
    - OPENCV_BRANCH=master
    - OPENCV_BRANCH=3.4
before_script:
    - git clone --single-branch --branch ${OPENCV_BRANCH} https://github.com/opencv/opencv.git
    - pushd opencv
    - mkdir build
    - cd build
    - cmake .. -DBUILD_LIST=core,imgproc,imgcodecs,calib3d,highgui -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=../install
    - cmake --build . --parallel 8 --target install --config Release
    - popd
script:
    - mkdir -p build
    - cd build
    - export CMAKE_MODULE_PATH=$(basename $(find ../opencv/install -name OpenCVConfig.cmake | head -n1))
    - echo "opencv $CMAKE_MODULE_PATH"
    - cmake ..
    - cmake --build .
    - echo | ./demo
